### ISSUE TITLE
Create a new Contributing page

### ISSUE THREAD

**Issue by zenorocha** [webcomponents/webcomponents.github.io#232]
We could add a new page grouped under "Community" that would describe what a person can do to help this project. Encouraging them to publish new articles, adding new talks and podcasts, updating browser support, etc.

**Comment by zenorocha** [comment]
@Nevraeka, since you've started to contribute a lot recently, would you be up to create this page?

**Comment by Nevraeka** [comment]
My pleasure

**Comment by Nevraeka** [comment]
As far as helping people contribute, is this be intended as a group of tutorials or as a summary?

**Comment by Nevraeka** [comment]
hopefully I can do a mockup or 2 in the next week

**Comment by zenorocha** [comment]
Any news on this?

**Comment by Nevraeka** [comment]
Dropped the ball on this one. I'll get something together as soon as I can. I just need to find the time to do it. So I'll comment again on my status by Wed if that's ok.

**Comment by Nevraeka** [comment]
Here is my update for today - I was thinking of making this page similar in layout to our 'resources' section but with a few differences.
 
- a left rail (rather than a right rail)
- two sections to the left rail
  - quick navigation links to steps in the contrib process in the main section
  - external links, assets, and resources in the bottom section
- the main content would be an longer form of the contributions.md that is easy to follow and with some graphical assets to show steps or relevant visuals (maybe)

no mock up or content yet but that is what I'm thinking. Any concerns or thoughts on this?

**Comment by Nevraeka** [comment]
@zenorocha  - Any preferences or gotchas to my proposal above? I am home next week so I can start working on this.

**Comment by Nevraeka** [comment]
@zenorocha should we close this ticket or continue on?

**Comment by Nevraeka** [comment]
closing due to new redesign in progress
