### ISSUE TITLE
Add SkateJS to the list of libraries.

### ISSUE THREAD

**Issue by treshugart** [webcomponents/webcomponents.github.io#249]
Hey guys, forgive me if I should be doing this differently. I read the [contributing guidelines](https://github.com/webcomponents/webcomponents.github.io/blob/site/CONTRIBUTING.md) and it didn't mention how I should go about adding a library. Feel free to tell me I'm wrong :)

I'm happy to submit a pull request if that's what you prefer for this sort of thing, but I figured you would probably want to screen the potential library first.

The library I would like to add is: https://github.com/skatejs/skatejs. We're using it at Atlassian for building web components and have been using it successfully for some time now.

Let me know if there's anything I can do. Cheers.

**Comment by Nevraeka** [comment]
@treshugart So many great libraries and collections are popping up all the time, Maple, Supersonic, & Strand to name a few. I am not sure if it is as simple as adding each one to the home page list. I struggle trying to figure out where the best place is to showcase these.

We could have a section in the right rail of the resources section devoted to collections & and one for libraries but I fear that will become cumbersome quickly. The same is likely on the home page.

@zenorocha - Maybe we could do a total overhaul to the resources section to make more versatile in this respect. Otherwise we should rethink the navigation & content strategies for these types of items

**Comment by Nevraeka** [comment]
Maybe we can create a pinterest-like board with resources such as libs, frameworks, projects, etc. Thoughts @zenorocha @addyosmani @PascalPrecht ?

**Comment by treshugart** [comment]
Had a chat with @Nevraeka tonight. There were a couple of options thrown around:

1. Follow the current convention and add it to the list of libraries and add a link to the docs from the resources page.
2. Refactor the resources section to add a section for libraries effectively giving it more real estate for libraries.

Number 1 has downsides as it makes the list longer on the home page. Number 2, though, would require a lot more work and work that I don't feel I'm qualified to be doing, though, I'm more than happy to help with fleshing out and coding if need be in the long run.

I've decided to go with number 1 for now as, at the very least, it follows the current convention and it can be adapted at a later point as it seems that it is something that will happen anyways. Kaizen :)

PR incoming soon.

**Comment by Nevraeka** [comment]
Thanks @treshugart
