### ISSUE TITLE
Please add http://www.material-design-lite.pub/ MDL/Dart to your site

### ISSUE THREAD

**Issue by MikeMitterer** [webcomponents/webcomponents.github.io#283]
Hi guys, can you please add my site.

MDL/Dart is quite flexible how to write components.
Sample where classname defines the component: http://www.material-design-lite.pub/#/accordion
Sample where attribute defines the component: http://www.material-design-lite.pub/#/model
Sample wehre tag defines the component: http://www.material-design-lite.pub/#/observe

It's all just about JS on your site but there is more!!! Please support Dart also!
Thanks

**Comment by zenorocha** [comment]
Hey @MikeMitterer,

Congratulations, it's a pretty nice project!

Unfortunately we cannot add it because this is a place to discuss and highlight Web Components only. If you're not sure about what is Web Components I'd recommend you to check: http://webcomponents.org/articles/why-web-components/

Thanks!

**Comment by MikeMitterer** [comment]
@zenorocha Thanks for your answer but you are right - it's not clear to me when a Component is a Web Component and when not. In my understanding the MDL Components ARE Web Components... Is "Shadow DOM" and "HTML Imports" a must for WC's?

**Comment by zenorocha** [comment]
Yes, they are.
