### ISSUE TITLE
[content] Add Polymer w/ SystemJS & TypeScript

### ISSUE THREAD

**Issue by Nevraeka** [webcomponents/webcomponents.github.io#295]
[http://blog.charto.net/typescript/Taming-Polymer-with-SystemJS-and-TypeScript-part-1/](http://blog.charto.net/typescript/Taming-Polymer-with-SystemJS-and-TypeScript-part-1/)

**Comment by jjrv** [comment]
Twitter: @chartojs (not used much yet)
Stackoverflow: http://stackoverflow.com/users/16509/jjrv
Short bio: Programmer and founder at BusFaster Ltd, creating web map tools with TypeScript and asm.js. Always looking into new technology, ever since getting a Commodore 128 way back.

Could try to find a decent photo soon to update the Github pic, but maybe not needed for now?

**Comment by Nevraeka** [comment]
thank you @jjrv . I'll add it asap
