### ISSUE TITLE
"Nowadays, Bower is the most popular package manager"

### ISSUE THREAD

**Issue by lastmjs** [webcomponents/webcomponents.github.io#322]
This [page](http://webcomponents.org/resources/) recommends Bower as the most popular front-end package manager. I think it is agreed that this is changing. I know Polymer is in the process of switching, see [this issue](https://github.com/Polymer/polymer/issues/2578) and [this issue](https://github.com/Polymer/polymer/issues/326). Just wanted to bring up a potential change in wording as the switch to npm seems to be imminent. It would be nice to perhaps explain this situation a little bit, instead of continuing newcomers' faith in Bower as the best package manager moving forward.

**Comment by Nevraeka** [comment]
@lastmjs Today because of the issues you cited - Polymer has no choice but to use Bower. That is not to say that you can't use JSPM or NPM for other web components. @RevillWeb is using JSPM/System for his vanilla components. I'm using NPM/WebPack & Bower (for Polymer) for mine so I think this is still relevant. I'd love to read a blog post on the ways we load these components from various package systems. Maybe we can reword the page a bit better to suggest more options without making it a giant post on package management and implementation cases. thoughts?

**Comment by Nevraeka** [comment]
Also [customelements.io](customelements.io) currently uses bower for discoverability....sadly

**Comment by lastmjs** [comment]
Maybe something like:
"Currently most web components libraries have great support for Bower, that's why we recommend you to use it. Keep in mind that Bower is not the only package manager for front-end code..." and then perhaps very briefly explain the role that NPM is/will be playing in front-end package management?

**Comment by zenorocha** [comment]
@Nevraeka CustomElements.io fetches both bower and npm packages since last year.

@lastmjs could you send a PR with this change?

**Comment by Nevraeka** [comment]
Thank you @zenorocha for clarifying. Good to know

**Comment by lastmjs** [comment]
@zenorocha I'm on it
